/**
 * C-suite and executive position titles for validation and extraction.
 * Used to identify leadership/decision-maker roles when scraping team pages.
 *
 * Total: ~155 titles
 *
 * DO NOT EDIT MANUALLY - extend as needed when new titles are encountered.
 */

export const EXECUTIVE_TITLES = new Set([
  // C-suite abbreviations
  "ceo",
  "cfo",
  "coo",
  "cto",
  "cio",
  "cmo",
  "chro",
  "clo",
  "cro",
  "cno",
  "cso",
  "cpo",
  "cdo",
  "cae",
  "ciso",
  "cbo",
  // Chief X Officer (full forms)
  "chief executive officer",
  "chief financial officer",
  "chief operating officer",
  "chief technology officer",
  "chief information officer",
  "chief marketing officer",
  "chief human resources officer",
  "chief legal officer",
  "chief revenue officer",
  "chief nursing officer",
  "chief strategy officer",
  "chief product officer",
  "chief digital officer",
  "chief data officer",
  "chief customer officer",
  "chief compliance officer",
  "chief administrative officer",
  "chief development officer",
  "chief growth officer",
  "chief innovation officer",
  "chief risk officer",
  "chief security officer",
  "chief sustainability officer",
  "chief diversity officer",
  "chief people officer",
  "chief experience officer",
  "chief commercial officer",
  "chief sales officer",
  "chief creative officer",
  "chief communications officer",
  "chief of staff",
  "chief investment officer",
  "chief procurement officer",
  "chief supply chain officer",
  "chief accounting officer",
  "chief audit executive",
  "chief learning officer",
  "chief ethics officer",
  "chief transformation officer",
  "chief information security officer",
  "chief impact officer",
  "chief brand officer",
  "chief culture officer",
  // President / Vice President
  "president",
  "vice president",
  "executive vice president",
  "senior vice president",
  "associate vice president",
  "evp",
  "svp",
  "avp",
  "vp",
  "president and ceo",
  "president and coo",
  "president & ceo",
  "president & coo",
  "chairman",
  "chairwoman",
  "chair",
  "chairperson",
  "board chair",
  // Founder / Owner
  "founder",
  "co-founder",
  "cofounder",
  "founding partner",
  "owner",
  "owner and operator",
  "proprietor",
  "managing owner",
  // Director
  "director",
  "executive director",
  "associate director",
  "senior director",
  "regional director",
  "managing director",
  // Partner / Principal
  "partner",
  "managing partner",
  "senior partner",
  "equity partner",
  "principal",
  "managing principal",
  "senior principal",
  // General / Manager (executive level)
  "general manager",
  "general counsel",
  "managing member",
  // Industry-specific executive titles
  "broker",
  "managing broker",
  "broker of record",
  "agent",
  "senior agent",
  "realtor",
  "managing realtor",
  // Other executive
  "treasurer",
  "secretary",
  "controller",
  "comptroller",
  "managing editor",
  "editor in chief",
  "publisher",
  "dean",
  "provost",
  "chancellor",
  "superintendent",
  "commissioner",
  "administrator",
  "executive",
  "country manager",
  "division president",
  "group president",
  "regional president",
  "business unit president",
  "co-ceo",
  "co-cfo",
  "interim ceo",
  "acting ceo",
  "deputy ceo",
  "assistant vice president",
  "assistant director",
  "deputy director",
  "vice chair",
  "vice chairman",
  "vice chairwoman",
  "deputy chair",
  "lead director",
  "independent director",
  "non-executive director",
  "non-executive chairman",
]);
