/**
 * Generic job titles and associated words for validation and extraction.
 * Used to distinguish non-executive roles when scraping team/contact pages.
 * Complements executive-titles.ts (executive = decision-makers; generic = broader roles).
 *
 * Total: ~200 entries
 *
 * DO NOT EDIT MANUALLY - extend as needed when new titles are encountered.
 */

export const JOB_TITLES = new Set([
  // Manager (non-executive)
  "manager",
  "assistant manager",
  "associate manager",
  "department manager",
  "project manager",
  "product manager",
  "program manager",
  "account manager",
  "sales manager",
  "operations manager",
  "office manager",
  "store manager",
  "branch manager",
  "team manager",
  "shift manager",
  "area manager",
  "district manager",
  "regional manager",
  "senior manager",
  "junior manager",
  // Supervisor
  "supervisor",
  "team lead",
  "team leader",
  "lead",
  "senior lead",
  "shift supervisor",
  "department supervisor",
  "crew chief",
  "foreman",
  "forewoman",
  // Analyst / Specialist
  "analyst",
  "senior analyst",
  "junior analyst",
  "business analyst",
  "data analyst",
  "financial analyst",
  "research analyst",
  "systems analyst",
  "specialist",
  "senior specialist",
  "technical specialist",
  "subject matter expert",
  "sme",
  // Coordinator
  "coordinator",
  "project coordinator",
  "program coordinator",
  "event coordinator",
  "administrative coordinator",
  "sales coordinator",
  "marketing coordinator",
  // Representative / Associate
  "representative",
  "sales representative",
  "customer service representative",
  "account representative",
  "associate",
  "sales associate",
  "retail associate",
  "legal associate",
  "research associate",
  "junior associate",
  "senior associate",
  // Technician / Technologist
  "technician",
  "senior technician",
  "lead technician",
  "field technician",
  "service technician",
  "maintenance technician",
  "it technician",
  "technologist",
  "medical technologist",
  // Assistant
  "assistant",
  "administrative assistant",
  "executive assistant",
  "office assistant",
  "sales assistant",
  "legal assistant",
  "research assistant",
  "teaching assistant",
  "ta",
  // Engineer (individual contributor)
  "engineer",
  "software engineer",
  "mechanical engineer",
  "electrical engineer",
  "civil engineer",
  "project engineer",
  "field engineer",
  "sales engineer",
  "junior engineer",
  "senior engineer",
  "staff engineer",
  "principal engineer",
  // Developer / Programmer
  "developer",
  "software developer",
  "web developer",
  "application developer",
  "senior developer",
  "junior developer",
  "programmer",
  // Designer
  "designer",
  "graphic designer",
  "web designer",
  "ux designer",
  "ui designer",
  "product designer",
  "interior designer",
  "senior designer",
  // Consultant
  "consultant",
  "senior consultant",
  "independent consultant",
  "business consultant",
  "management consultant",
  // Admin / Support
  "administrator",
  "system administrator",
  "network administrator",
  "database administrator",
  "office administrator",
  "support",
  "support specialist",
  "customer support",
  "technical support",
  "help desk",
  // Clerk / Reception
  "clerk",
  "office clerk",
  "file clerk",
  "receptionist",
  "front desk",
  "secretary",
  "administrative secretary",
  // Intern / Entry-level
  "intern",
  "internship",
  "trainee",
  "apprentice",
  "entry level",
  "junior",
  "entry-level",
  // Industry-specific generic roles
  "agent",
  "sales agent",
  "customer service agent",
  "claims agent",
  "broker",
  "loan officer",
  "underwriter",
  "processor",
  "inspector",
  "estimator",
  "driver",
  "operator",
  "machine operator",
  "installer",
  "technician",
  "mechanic",
  "electrician",
  "plumber",
  "carpenter",
  "painter",
  "roofer",
  "laborer",
  "worker",
  "crew member",
  "team member",
  "staff member",
  // Associated words (context)
  "employee",
  "staff",
  "worker",
  "contractor",
  "freelancer",
  "consultant",
  "temp",
  "temporary",
  "part-time",
  "full-time",
  "volunteer",
  "intern",
  "trainee",
  "apprentice",
  "team",
  "department",
  "division",
  "unit",
  "crew",
  "workforce",
  "personnel",
  "headcount",
  "hiring",
  "open position",
  "job opening",
  "careers",
  "join our team",
  "we're hiring",
  "now hiring",
]);
