// Mapping of transaction names to their tombstone image files.
// Sourced from Tombstone - web folder; kept in sync with api/prisma/tombstone-images.json for seeding.
export const tombstoneImages: Record<string, string> = {
  'IQDestinations': '/tombstones/IQDestinations.jpg',
  'Sim Author': '/tombstones/Sim-Author.jpg',
  'Sound Perfection, Inc': '/tombstones/Sound-Perfection-Inc.jpg',
  'Another Line, Inc': '/tombstones/Another-Line-Inc.jpg',
  'Hammers Quality Business Systems, Inc': '/tombstones/Hammers-Quality-Business-Systems-Inc.jpg',
  'SAULS Seismic, Inc': '/tombstones/SAULS-Seismic-Inc.jpg',
  'BLR Further': '/tombstones/BLR-Further.jpg',
  'Mossberg Sanitation, Inc. and Midwest Sanitation Co., Inc': '/tombstones/Mossberg-Sanitation-Inc-and-Midwest-Sanitation-Co-Inc.jpg',
  'Rocky Mountains Medical Equipment, Inc': '/tombstones/Rocky-Mountains-Medical-Equipment-Inc.jpg',
  'RECON Petrotechnologies, Inc': '/tombstones/RECON-Petrotechnologies-Inc.jpg',
  'Jim Myers Drug, Inc': '/tombstones/Jim-Myers-Drug-Inc.jpg',
  'Signal One Fire and Communication': '/tombstones/Signal-One-Fire-and-Communication.jpg',
  'Burlington Pharmacy Health Care': '/tombstones/Burlington-Pharmacy-Health-Care.jpg',
  'Essco Discount Drug Center': '/tombstones/Essco-Discount-Drug-Center.jpg',
  'Gulf & Basco': '/tombstones/Gulf-Basco.jpg',
  'Permian Fabrication and Services': '/tombstones/Permian-Fabrication-and-Services.jpg',
  'West Texas Plastics': '/tombstones/West-Texas-Plastics.jpg',
  'UCH Pharmaceutical Services': '/tombstones/UCH-Pharmaceutical-Services.jpg',
  'Vancouver Oil Company': '/tombstones/Vancouver-Oil-Company.jpg',
  'Bond Coat, Inc': '/tombstones/Bond-Coat-Inc.jpg',
  'Oil Works, Inc': '/tombstones/Oil-Works-Inc.jpg',
  'Bid4Vacations': '/tombstones/Bid4Vacations.jpg',
  'Asher Agency, Inc': '/tombstones/Asher-Agency-Inc.jpg',
  'Whitworth Tool, Inc': '/tombstones/Whitworth-Tool-Inc.jpg',
  "The Arnold Agency": '/tombstones/The-Arnold-Agency.jpg',
  "Johnson's Corner": '/tombstones/Johnson-s-Corner.jpg',
  'DI Digital Imaging and Laser Products, Inc.': '/tombstones/DI-Digital-Imaging-and-Laser-Products-Inc.jpg',
  'Marc USA': '/tombstones/Marc-USA.jpg',
  'OnePoint BPO Services, LLC': '/tombstones/OnePoint-BPO-Services-LLC.jpg',
  'BBB Tank Services, Inc': '/tombstones/BBB-Tank-Services-Inc.jpg',
  'Majewski Transportation': '/tombstones/Majewski-Transportation.jpg',
  'Ceres Technology Group': '/tombstones/Ceres-Technology-Group.jpg',
  'Breckenbridge Ski Enterprises': '/tombstones/Breckenbridge-Ski-Enterprises.jpg',
  'Colorado Lining International, Inc': '/tombstones/Colorado-Lining-International-Inc.jpg',
  'Metro State Fire': '/tombstones/Metro-State-Fire.jpg',
  'Key Enterprises, Inc.': '/tombstones/Key-Enterprises-Inc.jpg',
  'Pacific Cabinets, Inc.': '/tombstones/Pacific-Cabinets-Inc.jpg',
  'Twilight Services': '/tombstones/Twilight-Services.jpg',
  'Fire Protection Concepts, Inc': '/tombstones/Fire-Protection-Concepts-Inc.jpg',
  'JOBS-AMST': '/tombstones/JOBS-AMST.jpg',
  'PCS Mobile': '/tombstones/PCS-Mobile.jpg',
  'SWM International, Inc': '/tombstones/SWM-International-Inc.jpg',
  'Brenneco Fire Protection': '/tombstones/Brenneco-Fire-Protection.jpg',
  'Uniform Technology': '/tombstones/Uniform-Technology.jpg',
  'Florida Fire Service': '/tombstones/Florida-Fire-Service.jpg',
  'P&J Sprinkler Company, Inc': '/tombstones/PJ-Sprinkler-Company-Inc.jpg',
  'Big Bear Air Conditioning and Heating': '/tombstones/Big-Bear-Air-Conditioning-and-Heating.jpg',
  'Kennebec Fire Equipment, Inc': '/tombstones/Kennebec-Fire-Equipment-Inc.jpg',
  'KMS, Inc': '/tombstones/KMS-Inc.jpg',
  'New West Oil Company': '/tombstones/New-West-Oil-Company.jpg',
  'Remote Learner': '/tombstones/Remote-Learner.jpg',
  'Murray Smith, Inc': '/tombstones/Murray-Smith-Inc.jpg',
  'Northshore Fire Equipment': '/tombstones/Northshore-Fire-Equipment.jpg',
  'North American Refrigeration': '/tombstones/North-American-Refrigeration.jpg',
  'Zunesis': '/tombstones/Zunesis.jpg',
  'Boss Paint & Body': '/tombstones/Boss-Paint-Body.jpg',
  'Integrity Fire Safety Services': '/tombstones/Integrity-Fire-Safety-Services.jpg',
  'Henry Smith Plumbing, Heating': '/tombstones/Henry-Smith-Plumbing-Heating.jpg',
  'Colorado Storage Systems': '/tombstones/Colorado-Storage-Systems.jpg',
  'SWC, Inc': '/tombstones/SWC-Inc.jpg',
  'Certified Auto Body Center': '/tombstones/Certified-Auto-Body-Center.jpg',
  'Delta Fire Protection & Equipment': '/tombstones/Delta-Fire-Protection-Equipment.jpg',
  'Coldstar Inc': '/tombstones/Coldstar-Inc.jpg',
  'General Fire Sprinkler Company LLC': '/tombstones/General-Fire-Sprinkler-Company-LLC.jpg',
  'Strategic Merchandise Group': '/tombstones/Strategic-Merchandise-Group.jpg',
  'Stratified Environmental': '/tombstones/Stratified-Environmental.jpg',
  'Biome Consulting Group': '/tombstones/Biome-Consulting-Group.jpg',
  'Ecological Resource Consultants, Inc': '/tombstones/Ecological-Resource-Consultants-Inc.jpg',
  'Top Gun': '/tombstones/Top-Gun.jpg',
  'GoGreen Lawn Services': '/tombstones/GoGreen-Lawn-Services.jpg',
  'PEI': '/tombstones/PEI.jpg',
  'Maple Grove Auto': '/tombstones/Maple-Grove-Auto.jpg',
  'ATI Electrical Supply': '/tombstones/ATI-Electrical-Supply.jpg',
  'Henrichsens Fire and Safety Equipment Co': '/tombstones/Henrichsens-Fire-and-Safety-Equipment-Co.jpg',
  'Ian Vincent & Associates Environmental Consulting Services': '/tombstones/Ian-Vincent-Associates-Environmental-Consulting-Services.jpg',
  'AWE Air Water Energy': '/tombstones/AWE-Air-Water-Energy.jpg',
  'The Specialists Automotive and Truck': '/tombstones/The-Specialists-Automotive-and-Truck.jpg',
  'Precision Auto Works': '/tombstones/Precision-Auto-Works.jpg',
  'Stillwater Auto Clinic': '/tombstones/Stillwater-Auto-Clinic.jpg',
  'AEG Petroleum LLC': '/tombstones/AEG-Petroleum-LLC.jpg',
  'MEC Builds': '/tombstones/MEC-Builds.jpg',
  'Reliable Auto Care': '/tombstones/Reliable-Auto-Care.jpg',
  'ThriveMD-Platt Park & Formula Wellness': '/tombstones/ThriveMD-Platt-Park-Formula-Wellness.jpg',
  'Denver Plumbing & HVAC': '/tombstones/Denver-Plumbing-HVAC.jpg',
  'PODs Complete Car Care and Accessories': '/tombstones/PODs-Complete-Car-Care-and-Accessories.jpg',
  'Cummings Electric': '/tombstones/Cummings-Electric.jpg',
  'Precision Pool and Spa': '/tombstones/Precision-Pool-and-Spa.jpg',
  'World Resources Distribution': '/tombstones/World-Resources-Distribution.jpg',
};

export function getTombstoneImage(transactionName: string): string | undefined {
  return tombstoneImages[transactionName];
}
