// Mapping of transaction names to their tombstone image files
export const tombstoneImages: Record<string, string> = {
  'World Resources Distribution': '/tombstones/World-Resources-Distribution-tombstone-391x450.jpg',
  'Precision Pool and Spa': '/tombstones/Precision-Pool-and-Spa-tombstone-391x450.jpg',
  '5th Gear Auto': '/tombstones/5th-Gear-Auto-tombstone-391x450.jpg',
  'Cummings Electric': '/tombstones/Cummings-Electric-tombstone-391x450.jpg',
  'Pods Complete Car Care': '/tombstones/Pods-Complete-Car-Care-and-Accessories-tombstone-1-391x450.jpg',
  'Prime Home Services Group': '/tombstones/Prime-Home-Services-Group-tombstone-391x450.jpg',
  'ThriveMD': '/tombstones/ThriveMD-tombstone-391x450.jpg',
  'Reliable Auto Care': '/tombstones/Reliable-Auto-Care-tombstone-391x450.jpg',
  'AEG Plexus': '/tombstones/AEG-Plexus-tombstone-391x450.jpg',
  'MEC': '/tombstones/MEC-tombstone-391x450.jpg',
  'Stillwater Auto Clinic': '/tombstones/Stillwater-Auto-Clinic-tombstone-391x450.jpg',
  'Precision Auto Works': '/tombstones/Precision-Auto-Works-tombstone-391x450.jpg',
  'The Specialists Automotive and Truck': '/tombstones/The-Specialists-Automotive-and-Truck-tombstone-391x450.jpg',
  'AWE Air Water Energy': '/tombstones/AWE-Air-Water-Energy-tombstone-391x450.jpg',
  'Ian Vincent and Associates': '/tombstones/Ian-Vincent-Associates-Environmental-Consulting-Services-391x450.jpg',
  'Henrichsens Fire and Safety Equipment Co': '/tombstones/Henrichsens-Fire-and-Safety-Equipment-Co-tombstone-391x450.jpg',
  'ATI Electrical Supply': '/tombstones/ATI-Electrical-Supply-tombstone-391x450.jpg',
  'Maple Grove Auto Service': '/tombstones/Maple-Grove-Auto-tombstone-391x450.jpg',
  'Go Green Lawn Services': '/tombstones/GoGreen-Lawn-Services-tombstone-391x450.jpg',
  'PEI': '/tombstones/PEI-391x450.jpg',
  'Top Gun Collision Repair': '/tombstones/Top-Gun-Collision-Experts-tombstone-391x450.jpg',
  'Biome Consulting Group': '/tombstones/Biome-Consulting-Group-tombstone-391x450.jpg',
  'Ecological Resource Consultants Inc': '/tombstones/Ecological-Resource-Consultants-Inc-391x450.jpg',
  'Stratified Environmental & Archaeological Services': '/tombstones/Stratified-Environmental-Archeological-Services-tombstone-391x450.jpg',
  'Strategic Merchandise Group': '/tombstones/tombstone-strategic-merchandise-group-391x450.jpg',
  'General Fire Sprinkler Company LLC': '/tombstones/General-Fire-Sprinkler-Company-LLC-tombstone-391x450.jpg',
  'Coldstar Inc.': '/tombstones/Coldstar-Inc-tombstone-391x450.jpg',
  'Certified Auto Body Center': '/tombstones/Certified-Auto-Body-Center-tombstone-391x450.jpg',
  'Delta Fire Protection': '/tombstones/DCA-Partners-tombstone-1-391x450.jpg',
  'Colorado Storage Systems': '/tombstones/Colorado-Storage-Systems-tombstone-391x450.jpg',
  'SWC': '/tombstones/Resource-Environmental-Solutions-tombstone-391x450.jpg',
  'Henry Smith': '/tombstones/Heartland-Home-Services-tombstone-391x450.jpg',
  'Boss Paint and Body': '/tombstones/Boss-Paint-and-Body-tombstone-391x450.jpg',
  'Zunesis': '/tombstones/Seasid-Equity-Partners-tombstone-391x450.jpg',
  'Arizona Verde Fire Protection Inc': '/tombstones/API-Western-Arizona-tombstone-2-391x450.jpg',
  'North American Refrigeration': '/tombstones/North-American-Refrigeration-tombstone-391x450.jpg',
  'North Shore Fire Equipment': '/tombstones/ai-north-shore-fire-1-fire-and-safety-equipment-tombstone-391x450.jpg',
  'Murraysmith Inc': '/tombstones/tombstone-consor-murraysmith-2-391x450.jpg',
  'Remote Learner': '/tombstones/learning-pool-tombstone-391x450.jpg',
  'New West Oil Company': '/tombstones/reladyne-new-west-oil-tombstone-391x450.jpg',
  'KMS Inc': '/tombstones/new-state-KMS-tombstone-391x450.jpg',
  'Kennebec Fire Equipment Inc': '/tombstones/ai-kennebec-tombstone-391x450.jpg',
  'Integrity Fire Safety Services': '/tombstones/walnut-grove-integrity-fire-tombstone-391x450.jpg',
  'Big Bear Air Conditioning and Heating': '/tombstones/trudela-bigbear-tombstone-391x450.jpg',
  'P and J Sprinkler Company Inc': '/tombstones/pj-sprinkler-tombstone-391x450.jpg',
  'Florida Fire Services Inc': '/tombstones/tombstone_Florida-fire-service-391x450.jpg',
  'Uniform Technology': '/tombstones/tombstone_uniform_technology-391x450.jpg',
  'Brenneco Fire Protection': '/tombstones/TSCP-acquires-Brenneco-Fire-391x450.jpg',
  'SWM International Inc': '/tombstones/tombstone-pelican-391x450.jpg',
  'JOBS-AMST': '/tombstones/tombstone-keystone-jobs-amst-391x450.jpg',
  'Portable Computer Systems Inc': '/tombstones/tombstone-route1-391x450.jpg',
  'West Texas Plastics': '/tombstones/tombstone_wtp-2-391x450.jpg',
  'Marc USA': '/tombstones/MARC-USA-391x450.jpg',
  'BBB Tank Services Inc': '/tombstones/BBB-Tank-391x450.jpg',
  'Twilight Services': '/tombstones/tombstone-twilight-services-2-391x450.jpg',
  'Majewski Transportation Inc': '/tombstones/Majewski-391x450.jpg',
  'Fire Protection Concepts Inc': '/tombstones/tombstone-fire-protection-concepts-391x450.jpg',
  'Colorado Lining International Inc': '/tombstones/tombstone-colorado-lining-intl-391x450.jpg',
  'One Point BPO Services LLC': '/tombstones/tombstone_one-point-391x450.jpg',
  'Sauls Seismic Inc': '/tombstones/tombstone_sauls-2-391x450.jpg',
  'IQ Destinations': '/tombstones/tombstones_iqdestinations-2-391x450.jpg',
  'Ceres Technology Group Inc': '/tombstones/Ceres-391x450.jpg',
  'Pacific Cabinets Inc': '/tombstones/tombstone_pacific-cabinets-1-391x450.jpg',
  'Sound Perfection Inc': '/tombstones/tombstone_sound-perfection-2-391x450.jpg',
  'Another Line Inc': '/tombstones/tombstone_another-line-2-391x450.jpg',
  'Mossberg and Midwest Sanitation': '/tombstones/tombstone_mossberg-2-391x450.jpg',
  'Metro State Fire': '/tombstones/tombstone_metro-fire-2-391x450.jpg',
  'Whitworth Tool Inc': '/tombstones/tombstone_whitworth-2-391x450.jpg',
  'Inter-American Oil Works Inc': '/tombstones/tombstone_owi-2-391x450.jpg',
  'Permian Fabrication and Services': '/tombstones/tombstone_nov-2-391x450.jpg',
  'Rocky Mountain Medical Equipment Inc': '/tombstones/tombstone_rocky-mountain-2-391x450.jpg',
  'RECON Petrotechnologies Inc': '/tombstones/tombstone_recon-1-391x450.jpg',
  'Key Enterprises Inc': '/tombstones/tombstone_key-enterprises-2-391x450.jpg',
  'Johnsons Corner': '/tombstones/tombstone_johnsons-1-391x450.jpg',
  'Jim Myers Drug Inc': '/tombstones/tombstone_jim-myers-2-391x450.jpg',
  'Hammers Quality Business Systems Inc': '/tombstones/tombstone_hammers-1-391x450.jpg',
  'Gulf and Basco': '/tombstones/tombstone_gulf-basco-2-391x450.jpg',
  'Essco Discount Drug Center': '/tombstones/tombstone_essco-2-391x450.jpg',
  'BLR Further LLC': '/tombstones/tombstone_eastport-2-391x450.jpg',
  'Digital Imaging and Laser Products Inc': '/tombstones/tombstone_di-laser-2-391x450.jpg',
  'Burlington Pharmacy Health Care': '/tombstones/tombstone_burlington-2-391x450.jpg',
  'Bond Coat Inc': '/tombstones/tombstone_bond-coat-2-391x450.jpg',
  'Asher Agency Inc': '/tombstones/tombstone_asher-2-391x450.jpg',
  'The Arnold Agency Inc': '/tombstones/tombstone_arnold-2-391x450.jpg',
  'Signal One Fire and Communication LLC': '/tombstones/tombstone_api-2-391x450.jpg',
  'Breckenridge Ski Enterprises Inc': '/tombstones/tombstones_vail-resorts-1-391x450.jpg',
  'UCH Pharmaceutical Services Inc': '/tombstones/tombstone_uch-1-391x450.jpg',
  'Vancouver Oil Company Inc': '/tombstones/tombstone_vancouver-oil-1-391x450.jpg',
  'Bid 4 Vacations': '/tombstones/tombstones_bid4vacations-1-391x450.jpg',
  'Sim Author Inc': '/tombstones/tombstones_simauthor-1-391x450.jpg',
};

// Get tombstone image for a transaction, returns undefined if not found
export function getTombstoneImage(transactionName: string): string | undefined {
  return tombstoneImages[transactionName];
}
